backend:
  name: github
  repo: https://github.com/marquinhusgoncalves/gatsby-course
  branch: master
  site_domain: gatsby-marquinhus.netlify.app/

publish_mode: editorial_workflow
media_folder: "static/assets/img"
public_folder: "/assets/img"

collections:
  - label: "posts"
    name: "Posts"
    folder: "posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}_{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - {
          label: "Date",
          name: "date",
          widget: "datetime",
          format: "YYYY-MM-DD hh:mm:ss",
        }
      - { label: "Image", name: "thumbnail", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }
